### ISSUE TITLE
Just minor help [Solved]

### ISSUE THREAD

**Issue by Olykir** [AnIdiotsGuide/Tutorial-Bot#1]
is there nothing in the code to keep normal users from using it, when i used it in a test channel the bot reacted to me (i took the admin/mod role away) and it still responded, does it respond to my user id?

**Comment by realYusufR** [comment]
Well, to begin with, if you're server owner, you automatically override all permissions, regardless of roles.

I don't really see any code which restricts usage of the command based on which permissions the user has. I did find some stuff about `permLevel:` in `exports.conf` for most of the command files in the `commands` directory. However, at the moment, I'm not really familiar enough with Discord.js and Node as a whole to understand what this really does.

**Comment by realYusufR** [comment]
**Well, I took another look, and found this in [Line 19](https://github.com/AnIdiotsGuide/Tutorial-Bot/blob/Episode-8/commands/mute.js#L19) of `commands/mute.js`:**
```
if (!message.guild.member(client.user).hasPermission('MANAGE_ROLES_OR_PERMISSIONS')) return message.reply('I do not have the correct permissions.').catch(console.error);
```
But as I said before: 

> However, at the moment, I'm not really familiar enough with Discord.js and Node as a whole to understand what this really does.

**Comment by MayckGamer** [comment]
how i change the prefix?

**Comment by realYusufR** [comment]
@MayckGamer **The answer depends on which episode you are on:**

- If you are on Episode 5 or earlier, open up `app.js` and find the line of code which says `var prefix = "~"`. Change that code to `var prefix = "YOUR-PREFIX"`. So if I wanted my prefix to be `@`, I would write `var prefix = "@"`. *Note: Although a semicolon is currently not present, I would recommend adding one to the end of the line (like so: `var prefix = "@";`) for clarity.*

- If you are on Episode 6 or later, it's a bit easier. First, make sure that you have renamed `settings_example.json` to `settings.json` and filled in the `token`, `ownerid`, and other info. Then, find the line which says `"prefix": "YOURPREFIXGOESHERE",`, and replace it with *your* prefix.  So if I wanted my prefix to be `@`, I would write `"prefix": "@",`.

*By the way, I would recommend that if you have another question later, open a new issue/thread for it.*

**I hope this helped! :)**

**Comment by realYusufR** [comment]
**@YorkAARGH Can you please close this issue? Thanks! 👍 **

**Comment by MayckGamer** [comment]
As I add new commands pq when I put the error in. epsode 8

**Comment by YorkAARGH** [comment]
lol I wasn't even aware this was open LOL
