### ISSUE TITLE
Prefix var

### ISSUE THREAD

**Issue by hexagonbizkit** [AnIdiotsGuide/Tutorial-Bot#10]
Whenever I try and use the prefix var, even copy-pasting the code directly from here, the prefix never works.

**Comment by SybilSystem** [comment]
Add your code so we can help you.

**Comment by hexagonbizkit** [comment]
`const Discord = require('discord.js');
const client = new Discord.Client();
const settings = require('./settings.json');

client.on('ready',() => {
	console.log('I am on');
});

var Prefix = "~"
client.on('message', message => {
	if (message.author === client.user) return;
	if (message.content.startsWith(Prefix + 'ping')) {
		message.channel.sendMessage('pong');
	}
});

client.login(Settings.token);`

**Comment by SybilSystem** [comment]
Does your bot come online?

**Comment by hexagonbizkit** [comment]
```const Discord = require('discord.js');
const client = new Discord.Client();
const settings = require('./settings.json');

client.on('ready',() => {
	console.log('I am on');
});

var Prefix = "~"
client.on('message', message => {
	if (message.author === client.user) return;
	if (message.content.startsWith(Prefix + 'ping')) {
		message.channel.sendMessage('pong');
	}
});

client.login(Settings.token);`

**Comment by hexagonbizkit** [comment]
I did, it just wont show whenever I copy it into github for some reason.

**Comment by SXQHex** [comment]
could u try
`const Prefix = "~"`

**Comment by hexagonbizkit** [comment]
```js
if (message.content.startsWith(Prefix + 'ping'))
```

**Comment by kinect3000** [comment]
use "message.channel.send" " instead of message.channel.sendMessage
