### ISSUE TITLE
caseNumber crashing

### ISSUE THREAD

**Issue by SXQHex** [AnIdiotsGuide/Tutorial-Bot#13]
All commands that i use caseNumber is crashing.

caseNumber.js;............................
exports.caseNumber = (client, modlog) => {
  const messages = modlog.fetchMessages({limit:5});
  const log = messages.filter (m => m.author.id === client.user.id &&
    m.embeds[0] &&
    m.embeds[0].type ==='rich' &&
    m.embeds[0].footer &&
    m.embeds[0].footer.text.startsWith('Olay')
  ).first();
  if (!log) return 1;
  const thisCase = /Case\s(\d+)/.exec(log.embeds[0].footer.text);
  return thisCase ? parseInt (thisCase[1]) + 1 : 1;
};

Console Log;.................
const log = messages.filter (m => m.author.id === client.user.id &&
TypeError: messages.filter is not a function
at exports.caseNumber (D:\Dbots\myBot\util\caseNumber.js:3:24)
at Object.exports.run (D:\Dbots\myBot\commands\warn.js:10:19)
at Client.module.exports.message (D:\Dbots\myBot\events\message.js:17:9)
at emitOne (events.js:116:13)
at Client.emit (events.js:211:7)
at MessageCreateHandler.handle

**Comment by YorkAARGH** [comment]
You didn't await it, look [here](https://github.com/AnIdiotsGuide/Tutorial-Bot/blob/Episode-10-Part-2-Final-Episode/util/caseNumber.js#L2) to see what I mean.

**Comment by AnIdiotsGuide** [comment]
Issue resolved within the guild.
