### ISSUE TITLE
!mute

### ISSUE THREAD

**Issue by MayckGamer** [AnIdiotsGuide/Tutorial-Bot#2]
the mute not work for me. I am not the server administrator but the other commands works

**Comment by AnIdiotsGuide** [comment]
Are you able to give me anymore information than that? I won't be able to help without additional information.

**Comment by MayckGamer** [comment]
I put on a server that I'm not an administrator, So I can not give mute speech that I'm not allowed. But this only happens with the mute. Sorry for the English, Google Translator

**Comment by MayckGamer** [comment]
(node:1144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): DiscordAPIError: Missing Permissions

**Comment by MayckGamer** [comment]
error (node:1144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): DiscordAPIError: Missing Permissions

**Comment by AnIdiotsGuide** [comment]
It needs permissions to do whatever it is you're trying to get the bot to do
