### ISSUE TITLE
help command on dm 

### ISSUE THREAD

**Issue by alktbihd** [AnIdiotsGuide/Tutorial-Bot#8]
>   let mod_role = message.guild.roles.find('name', settings.modrolename);
                              ^
 
TypeError: Cannot read property 'roles' of null
    at Client.client.elevation.message [as elevation] (C:\Users\user\Desktop\Coding\tt\app.js:54:31)
    at Client.module.exports.message (C:\Users\user\Desktop\Coding\tt\events\message.js:8:22)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\user\Desktop\Coding\tt\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\user\Desktop\Coding\tt\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (C:\Users\user\Desktop\Coding\tt\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:325:35)
    at WebSocketConnection.onMessage (C:\Users\user\Desktop\Coding\tt\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:288:17)
    at WebSocket.onMessage (C:\Users\user\Desktop\Coding\tt\node_modules\ws\lib\EventTarget.js:103:16)
    at emitTwo (events.js:125:13)

**Comment by AnIdiotsGuide** [comment]
Thanks for bringing this to my attention, I will address it in the next video, it was a bit of an oversight on my half, to prevent the crash inside the bot ignore line, add `|| message.channel.type !== 'text`
